/* ==========================================================================
   Na jakých pozicích se který champion reálně hraje.
   --------------------------------------------------------------------------
   Data Dragon lajny neobsahuje (zná jen tagy typu Mage/Fighter), takže je
   tenhle seznam ruční. První pozice je ta hlavní.

   Champion, který tu chybí (třeba nově vydaný), dostane pozici odhadem
   z tagů a generátor na něj upozorní — pak ho sem dopiš.
   ========================================================================== */

module.exports = {
  Aatrox: ['TOP'],
  Ahri: ['MID'],
  Akali: ['MID', 'TOP'],
  Akshan: ['MID', 'TOP'],
  Alistar: ['SUPP'],
  Ambessa: ['TOP', 'JG'],
  Amumu: ['JG', 'SUPP'],
  Anivia: ['MID'],
  Annie: ['MID', 'SUPP'],
  Aphelios: ['ADC'],
  Ashe: ['ADC', 'SUPP'],
  AurelionSol: ['MID'],
  Aurora: ['MID', 'TOP'],
  Azir: ['MID'],
  Bard: ['SUPP'],
  Belveth: ['JG'],
  Blitzcrank: ['SUPP'],
  Brand: ['SUPP', 'MID'],
  Braum: ['SUPP'],
  Briar: ['JG'],
  Caitlyn: ['ADC'],
  Camille: ['TOP', 'JG'],
  Cassiopeia: ['MID', 'TOP'],
  Chogath: ['TOP', 'MID'],
  Corki: ['MID', 'ADC'],
  Darius: ['TOP'],
  Diana: ['JG', 'MID'],
  Draven: ['ADC'],
  DrMundo: ['TOP', 'JG'],
  Ekko: ['MID', 'JG'],
  Elise: ['JG'],
  Evelynn: ['JG'],
  Ezreal: ['ADC'],
  Fiddlesticks: ['JG', 'SUPP'],
  Fiora: ['TOP'],
  Fizz: ['MID'],
  Galio: ['MID', 'SUPP'],
  Gangplank: ['TOP'],
  Garen: ['TOP'],
  Gnar: ['TOP'],
  Gragas: ['JG', 'TOP', 'MID'],
  Graves: ['JG'],
  Gwen: ['TOP', 'JG'],
  Hecarim: ['JG'],
  Heimerdinger: ['MID', 'TOP', 'SUPP'],
  Hwei: ['MID', 'SUPP'],
  Illaoi: ['TOP'],
  Irelia: ['TOP', 'MID'],
  Ivern: ['JG'],
  Janna: ['SUPP'],
  JarvanIV: ['JG'],
  Jax: ['TOP', 'JG'],
  Jayce: ['TOP', 'MID'],
  Jhin: ['ADC'],
  Jinx: ['ADC'],
  Kaisa: ['ADC'],
  Kalista: ['ADC'],
  Karma: ['SUPP', 'MID'],
  Karthus: ['JG', 'MID'],
  Kassadin: ['MID'],
  Katarina: ['MID'],
  Kayle: ['TOP', 'MID'],
  Kayn: ['JG'],
  Kennen: ['TOP', 'MID'],
  Khazix: ['JG'],
  Kindred: ['JG'],
  Kled: ['TOP'],
  KogMaw: ['ADC'],
  KSante: ['TOP'],
  Leblanc: ['MID'],
  LeeSin: ['JG'],
  Leona: ['SUPP'],
  Lillia: ['JG'],
  Lissandra: ['MID'],
  Lucian: ['ADC', 'MID'],
  Lulu: ['SUPP'],
  Lux: ['SUPP', 'MID'],
  Malphite: ['TOP', 'SUPP'],
  Malzahar: ['MID'],
  Maokai: ['SUPP', 'JG', 'TOP'],
  MasterYi: ['JG'],
  Milio: ['SUPP'],
  MissFortune: ['ADC'],
  MonkeyKing: ['TOP', 'JG'],
  Mordekaiser: ['TOP'],
  Morgana: ['SUPP', 'MID'],
  Naafiri: ['MID', 'JG'],
  Nami: ['SUPP'],
  Nasus: ['TOP'],
  Nautilus: ['SUPP'],
  Neeko: ['MID', 'SUPP'],
  Nidalee: ['JG'],
  Nilah: ['ADC'],
  Nocturne: ['JG'],
  Nunu: ['JG'],
  Olaf: ['JG', 'TOP'],
  Orianna: ['MID'],
  Ornn: ['TOP'],
  Pantheon: ['SUPP', 'TOP', 'MID'],
  Poppy: ['JG', 'TOP', 'SUPP'],
  Pyke: ['SUPP'],
  Qiyana: ['MID'],
  Quinn: ['TOP'],
  Rakan: ['SUPP'],
  Rammus: ['JG'],
  RekSai: ['JG'],
  Rell: ['SUPP'],
  Renata: ['SUPP'],
  Renekton: ['TOP'],
  Rengar: ['JG', 'TOP'],
  Riven: ['TOP'],
  Rumble: ['TOP', 'MID'],
  Ryze: ['MID', 'TOP'],
  Samira: ['ADC'],
  Sejuani: ['JG'],
  Senna: ['SUPP', 'ADC'],
  Seraphine: ['SUPP', 'MID'],
  Sett: ['TOP', 'SUPP'],
  Shaco: ['JG', 'SUPP'],
  Shen: ['TOP', 'SUPP'],
  Shyvana: ['JG'],
  Singed: ['TOP'],
  Sion: ['TOP'],
  Sivir: ['ADC'],
  Skarner: ['JG', 'TOP'],
  Smolder: ['ADC'],
  Sona: ['SUPP'],
  Soraka: ['SUPP'],
  Swain: ['MID', 'SUPP'],
  Sylas: ['MID', 'JG'],
  Syndra: ['MID'],
  TahmKench: ['SUPP', 'TOP'],
  Taliyah: ['JG', 'MID'],
  Talon: ['MID', 'JG'],
  Taric: ['SUPP'],
  Teemo: ['TOP', 'JG'],
  Thresh: ['SUPP'],
  Tristana: ['ADC', 'MID'],
  Trundle: ['JG', 'TOP'],
  Tryndamere: ['TOP'],
  TwistedFate: ['MID'],
  Twitch: ['ADC', 'JG'],
  Udyr: ['JG'],
  Urgot: ['TOP'],
  Varus: ['ADC'],
  Vayne: ['ADC', 'TOP'],
  Veigar: ['MID'],
  Velkoz: ['MID', 'SUPP'],
  Vex: ['MID'],
  Vi: ['JG'],
  Viego: ['JG'],
  Viktor: ['MID'],
  Vladimir: ['MID', 'TOP'],
  Volibear: ['JG', 'TOP'],
  Warwick: ['JG', 'TOP'],
  Xayah: ['ADC'],
  Xerath: ['MID', 'SUPP'],
  XinZhao: ['JG'],
  Yasuo: ['MID', 'TOP'],
  Yone: ['MID', 'TOP'],
  Yorick: ['TOP'],
  Yuumi: ['SUPP'],
  Zac: ['JG', 'TOP'],
  Zed: ['MID'],
  Zeri: ['ADC'],
  Ziggs: ['MID', 'ADC'],
  Zilean: ['SUPP', 'MID'],
  Zoe: ['MID'],
  Zyra: ['SUPP'],

  /* --- novější, zatím podle toho, jak se hrají --- */
  Mel: ['MID'],
  Yunara: ['ADC'],
  Locke: ['MID'],
  Zaahen: ['JG']
};
